export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const LOAD_TAGS_SUCCESS = "LOAD_TAGS_SUCCESS";
export const LOAD_RECIPES_SUCCESS = "LOAD_RECIPES_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
